"""Runnable FP&A starter-kit vertical slice."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from kdaf.core import KdafCore


def run_starter_kit_demo(
    project_name: str = "FP&A Starter Kit Demo",
    config_path: str | Path | None = None,
    metadata_store_path: str | Path | None = None,
    dwh_store_path: str | Path | None = None,
    include_graph: bool = True,
) -> dict[str, Any]:
    """Create a project, load the starter kit, and return inspectable demo evidence."""

    core = KdafCore(config_path=config_path, metadata_store_path=metadata_store_path)
    project = core.create_project(
        name=project_name,
        description="Generated by the KDAF FP&A starter-kit demo.",
    )
    starter_kit = core.load_starter_kit(
        project_id=project["id"],
        dwh_store_path=dwh_store_path,
        include_graph=include_graph,
    )
    sample_facts = core.starter_dwh_sample_facts(dwh_store_path=dwh_store_path)
    questions = core.list_competency_questions(project_id=project["id"])
    mvg_artifacts = core.list_mvg_artifacts(project_id=project["id"])
    graph_context = (
        core.starter_graph_context()
        if include_graph
        else {"skipped": True, "reason": "Graph inspection was skipped by request"}
    )

    return {
        "project": project,
        "starter_kit": starter_kit,
        "dwh_sample_facts": sample_facts,
        "starter_questions": questions,
        "mvg_artifacts": mvg_artifacts,
        "graph_context": graph_context,
    }
